export default [
  {
    symbol: '$',
    currency: '$ USD',
    displayTitle: 'US Dollar',
    code: 'USD',
  },
  {
    symbol: '€',
    currency: '€ EURO',
    displayTitle: 'Euro',
    code: 'EUR',
  },
  {
    code: 'GBP',
    symbol: '£',
    currency: '£ GBP',
    displayTitle: 'GBP',
  },
  {
    code: 'INR',
    symbol: '₹',
    currency: '₹ INR',
    displayTitle: 'Indian Rupee',
  },
  {
    code: 'AUD',
    symbol: '$',
    currency: '$ AUD',
    displayTitle: 'AUD',
  },
  {
    code: 'BRL',
    symbol: 'R$',
    currency: 'R$ BRL',
    displayTitle: 'BRL',
  },
  {
    code: 'CAD',
    symbol: '$',
    currency: '$ CAD',
    displayTitle: 'CAD',
  },
  {
    code: 'CHF',
    symbol: '₣',
    currency: '₣ CHF',
    displayTitle: 'CHF',
  },
  {
    code: 'CLP',
    symbol: '$',
    currency: '$ CLP',
    displayTitle: 'CLP',
  },
  {
    code: 'CNY',
    symbol: '¥',
    currency: '¥ CNY',
    displayTitle: 'CNY',
  },
  {
    code: 'DKK',
    symbol: 'kr',
    currency: 'kr DKK',
    displayTitle: 'DKK',
  },
  {
    code: 'HKD',
    symbol: '$',
    currency: '$ HKD',
    displayTitle: 'HKD',
  },
  {
    code: 'ISK',
    symbol: 'kr',
    currency: 'kr ISK',
    displayTitle: 'ISK',
  },
  {
    code: 'JPY',
    symbol: '¥',
    currency: '¥ JPY',
    displayTitle: 'JPY',
  },
  {
    code: 'KRW',
    symbol: '₩',
    currency: '₩ KRW',
    displayTitle: 'KRW',
  },
  {
    code: 'NZD',
    symbol: '$',
    currency: '$ NZD',
    displayTitle: 'NZD',
  },
  {
    code: 'PLN',
    symbol: 'zł',
    currency: 'zł PLN',
    displayTitle: 'PLN',
  },
  {
    code: 'RUB',
    symbol: '₽',
    currency: '₽ RUB',
    displayTitle: 'RUB',
  },
  {
    code: 'SEK',
    symbol: 'kr',
    currency: 'kr SEK',
    displayTitle: 'SEK',
  },
  {
    code: 'SGD',
    symbol: '$',
    currency: '$ SGD',
    displayTitle: 'SGD',
  },
  {
    code: 'THB',
    symbol: '฿',
    currency: '฿ THB',
    displayTitle: 'THB',
  },
  {
    code: 'TRY',
    symbol: '₺',
    currency: '₺ TRY',
    displayTitle: 'TRY',
  },
  {
    code: 'TWD',
    symbol: '$',
    currency: '$ TWD',
    displayTitle: 'TWD',
  },
  {
    code: 'ZAR',
    symbol: 'R',
    currency: 'R ZAR',
    displayTitle: 'TWD',
  },
];
