# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new dev build to TestFlight"
  lane :dev do
    file_name = "../../.env"
    file_url = "https://raw.githubusercontent.com/bithyve/bitcoin-tribe-envs/DEVELOPMENT/.env.app"
    auth_header = "Authorization: token #{ENV["GITHUB_TOKEN"]}"
    sh(
      "curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'",
      step_name: "curl -H '***' -o '#{file_name}' -s '#{file_url}'"
    )
    increment_build_number(xcodeproj: "tribe.xcodeproj")

    get_certificates( # Create or get certificate, and install it
      development: true,
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )

    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )

    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "tribe.xcodeproj",
      target_filter: "tribe", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )

    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    build_app(workspace: "tribe.xcworkspace", scheme: "tribe-dev", clean: true,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
          CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) + " AppStore" # Value of this parameter is the name of the Provisioning Profile. By default, it will be "{bundleId} AppStore"
      }
    },
    build_path: "./builds",
    output_directory: "./builds")
    upload_to_testflight
    clean_build_artifacts
  end

  desc "Push a new live build to TestFlight"
  lane :live do
    file_name = "../../.env"
    file_url = "https://raw.githubusercontent.com/bithyve/bitcoin-tribe-envs/PRODUCTION/.env.app"
    auth_header = "Authorization: token #{ENV["GITHUB_TOKEN"]}"
    sh(
      "curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'",
      step_name: "curl -H '***' -o '#{file_name}' -s '#{file_url}'"
    )

    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )

    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "tribe_dist.mobileprovision" # Rename the local provisioning profile
    )

    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "tribe.xcodeproj",
      target_filter: "tribe", # Name of your project
      profile: "./builds/tribe_dist.mobileprovision",
      build_configuration: "Release"
    )

    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    build_app(workspace: "tribe.xcworkspace", scheme: "tribe", clean: true,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
          CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => "match AppStore com.bithyve.tribe"
      }
    },
    build_path: "./builds",
    output_directory: "./builds")
    upload_to_testflight
    clean_build_artifacts
  end

  desc "Push a new dev build to TestFlight (GitHub Actions)"
  lane :github_actions_dev do
    unless ENV["GITHUB_TOKEN"] && !ENV["GITHUB_TOKEN"].strip.empty?
    UI.user_error!("❌ GITHUB_TOKEN is missing. Exiting lane.")
    end
    UI.message("🔐 GITHUB_TOKEN is present")

    file_name = "../../.env"
    file_url  = "https://api.github.com/repos/bithyve/bitcoin-tribe-envs/contents/.env.app?ref=DEVELOPMENT"
    auth_header = "Authorization: token #{ENV["GITHUB_TOKEN"]}"
    UI.user_error!("❌ GITHUB_TOKEN missing") if ENV["GITHUB_TOKEN"].to_s.strip.empty?
    sh(
      %Q(
        curl -f -L \
          -H "Authorization: Bearer #{ENV['GITHUB_TOKEN']}" \
          -H "Accept: application/vnd.github.v3.raw" \
          -o "#{file_name}" \
          "#{file_url}"
      ),
      step_name: "Download .env from env repo"
      )

      UI.message("✅ .env download attempted")
    # ---- VERIFY FILE EXISTS ----
    if File.exist?(file_name)
      UI.success("✅ .env file exists at #{file_name}")
    else
      UI.user_error!("❌ .env file does NOT exist at #{file_name}")
    end

    # ---- VERIFY FILE IS NOT EMPTY ----
    content = File.read(file_name).strip

    if content.empty?
      UI.user_error!("❌ .env file is EMPTY")
    else
      UI.success("✅ .env file has content")
    end

    # ---- SAFE PREVIEW (no secrets leak) ----
    UI.message("🔎 .env preview (keys only):")

    content.each_line do |line|
      next if line.strip.empty? || line.start_with?("#")
      key = line.split("=").first
      UI.message("• #{key}=***")
    end
    # --------------

    ENV["FASTLANE_DISABLE_COLORS"] = "1"

    UI.message("APPLE_TEAM_ID env: #{ENV['APPLE_TEAM_ID'] ? 'SET' : 'MISSING'}")
    UI.message("APPLE_TEAM_ID length: #{ENV['APPLE_TEAM_ID']&.length}")

    api_key_path = File.expand_path("../fastlane/AuthKey.p8", __dir__)
    api_key = app_store_connect_api_key(
      key_id: ENV["FASTLANE_APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: api_key_path,
      is_key_content_base64: false
    )

    create_keychain(
      name: "temp_keychain",
      password: ENV["KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: "appstore",                     
      readonly: true,                       
      git_url: ENV["MATCH_GIT_URL"],        
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      team_id: ENV["APPLE_TEAM_ID"],
      keychain_name: "temp_keychain",
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

    build_app(
      workspace: "tribe.xcworkspace",
      scheme: "tribe-dev",
      clean: true,
      output_directory: "./builds",
      export_method: "app-store",
      xcargs: "-verbose"
    )
    upload_to_testflight(api_key: api_key)
    clean_build_artifacts
    build_number = get_build_number(xcodeproj: "tribe.xcodeproj")
    UI.success("✅ Dev build successfully uploaded to TestFlight! Build Number: #{build_number}")
  end
  
  desc "Push a new live build to TestFlight (GitHub Actions)"
  lane :github_actions_live do
    file_name = "../../.env"
    file_url = "https://raw.githubusercontent.com/bithyve/bitcoin-tribe-envs/PRODUCTION/.env.app"
    auth_header = "Authorization: token #{ENV["GITHUB_TOKEN"]}"
    sh(
      "curl -H '#{auth_header}' -o '#{file_name}' -s '#{file_url}'",
      step_name: "curl -H '***' -o '#{file_name}' -s '#{file_url}'"
    )

    ENV["FASTLANE_DISABLE_COLORS"] = "1"

    api_key_path = File.expand_path("../fastlane/AuthKey.p8", __dir__)
    api_key = app_store_connect_api_key(
      key_id: ENV["FASTLANE_APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: api_key_path,
      is_key_content_base64: false
    )
    match(
      type: "appstore",                     
      readonly: true,                       
      git_url: ENV["MATCH_GIT_URL"],        
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      team_id: ENV["APPLE_TEAM_ID"]
    )
    update_project_team(
      path: "tribe.xcodeproj",
      teamid: ENV["APPLE_TEAM_ID"]
    )
    build_app(
      workspace: "tribe.xcworkspace",
      scheme: "tribe",
      clean: true,
      export_method: "app-store",
      build_path: "./builds",
      output_directory: "./builds",
      export_options: {
        provisioningProfiles: {
          CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => "match AppStore com.bithyve.tribe"
        }
      }
    )
    upload_to_testflight(api_key: api_key)
    clean_build_artifacts
    build_number = get_build_number(xcodeproj: "tribe.xcodeproj")
    UI.success("✅ Live build successfully uploaded to TestFlight! Build Number: #{build_number}")
  end
end

after_all do |lane|
  buildNumber = get_build_number() 
  # slack(message: "Build success :rocket: \nBuild Number: " + buildNumber.to_s)
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success:false
    # )
  end
