export enum RealmSchema {
  TribeApp = 'TribeApp',
  Wallet = 'Wallet',
  WalletDerivationDetails = 'WalletDerivationDetails',
  WalletPresentationData = 'WalletPresentationData',
  BIP85Config = 'BIP85Config',
  UTXO = 'UTXO',
  UTXOInfo = 'UTXOInfo',
  Label = 'Label',
  Tags = 'Tags',
  Transaction = 'Transaction',
  TransactionToAddressMapping = 'TransactionToAddressMapping',
  WalletSpecs = 'WalletSpecs',
  DefaultNodeConnect = 'DefaultNodeConnect',
  NodeConnect = 'NodeConnect',
  AddressCache = 'AddressCache',
  VersionHistory = 'VersionHistory',
  RgbWallet = 'RgbWallet',
  ReceiveData = 'ReceiveData',
  Coin = 'Coin',
  Balance = 'Balance',
  AssetTransaction = 'AssetTransaction',
  MetaData = 'MetaData',
  Collectible = 'Collectible',
  CollectibleMedia = 'CollectibleMedia',
  BackupHistory = 'BackupHistory',
  CloudBackupHistory = 'CloudBackupHistory',
}
