import { MMKV } from 'react-native-mmkv';

const MMKVStorage = new MMKV();

export enum Keys {
  APPID = 'APPID',
  PIN_METHOD = 'PIN_METHOD',
  AVERAGE_TX_FEE_BY_NETWORK = 'AVERAGE_TX_FEE_BY_NETWORK',
  THEME_MODE = 'THEME_MODE',
  IS_USER_SELECT_THEME = 'IS_USER_SELECT_THEME',
  WALLET_BACKUP = 'WALLET_BACKUP',
  ASSET_BACKUP = 'ASSET_BACKUP',
  APP_LANGUAGE = 'APP_LANGUAGE',
  EXCHANGE_RATES = 'EXCHANGE_RATES',
  APP_CURRENCY = 'APP_CURRENCY',
  CURRENCY_MODE = 'CURRENCY_MODE',
  BACKUPALERT = 'BACKUPALERT',
  SETUPAPP = 'SETUPAPP',
  RGB_ASSET_RELAY_BACKUP = 'RGB_ASSET_RELAY_BACKUP',
  FCM_TOKEN = 'FCM_TOKEN',
  SHOW_WALLET_BACKUP_ALERT = 'SHOW_WALLET_BACKUP_ALERT',
  SERVICE_FEE = 'SERVICE_FEE',
  LAST_FCM_VERSION_TOPIC = 'LAST_FCM_VERSION_TOPIC',
  DISCLAIMER_VISIBILITY = 'DISCLAIMER_VISIBILITY',
  INVOICE_EXPIRY = 'INVOICE_EXPIRY',
  VERIFY_TWITTER_INFO = 'VERIFY_TWITTER_INFO',
  VERIFY_DOMAIN_INFO = 'VERIFY_DOMAIN_INFO',
  RATE_LIMIT_KEY = 'TWITTER_RATE_LIMIT_TIME',
  RATE_LIMITED_TWEET_URL_KEY = 'RATE_LIMITED_TWEET_URL',
  CLAIM_KEY = 'IS_CLAIMED',
  CLAIM_KEYCHAIN_ACCOUNT = 'CLAIM_STATUS',
}

export class Storage {
  static set = (key: Keys, value: string | number | boolean): void =>
    MMKVStorage.set(key, value);

  static clear = (): void => MMKVStorage.clearAll();

  static get = (key: Keys): string | undefined => MMKVStorage.getString(key);
}
