/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BackupRequest
 */
export interface BackupRequest {

    /**
     * @type {string}
     * @memberof BackupRequest
     * @example /path/where/to/save/the/backup/file
     */
    backupPath?: string;

    /**
     * @type {string}
     * @memberof BackupRequest
     * @example nodepassword
     */
    password?: string;
}
