/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Channel
 */
export interface Channel {

    /**
     * @type {string}
     * @memberof Channel
     * @example 8129afe1b1d7cf60d5e1bf4c04b09bec925ed4df5417ceee0484e24f816a105a
     */
    channelId?: string;

    /**
     * @type {string}
     * @memberof Channel
     * @example 5a106a814fe28404eece1754dfd45e92ec9bb0044cbfe1d560cfd7b1e1af2981
     */
    fundingTxid?: string;

    /**
     * @type {string}
     * @memberof Channel
     * @example 03b79a4bc1ec365524b4fab9a39eb133753646babb5a1da5c4bc94c53110b7795d
     */
    peerPubkey?: string;

    /**
     * @type {string}
     * @memberof Channel
     */
    peerAlias?: string;

    /**
     * @type {number}
     * @memberof Channel
     * @example 120946279120896
     */
    shortChannelId?: number;

    /**
     * @type {boolean}
     * @memberof Channel
     * @example false
     */
    ready?: boolean;

    /**
     * @type {number}
     * @memberof Channel
     * @example 30010
     */
    capacitySat?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 28616000
     */
    localBalanceMsat?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 21616000
     */
    outboundBalanceMsat?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 6394000
     */
    inboundBalanceMsat?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 3001000
     */
    nextOutboundHtlcLimitMsat?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 1
     */
    nextOutboundHtlcMinimumMsat?: number;

    /**
     * @type {boolean}
     * @memberof Channel
     * @example false
     */
    isUsable?: boolean;

    /**
     * @type {boolean}
     * @memberof Channel
     * @example true
     */
    _public?: boolean;

    /**
     * @type {string}
     * @memberof Channel
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    assetId?: string;

    /**
     * @type {number}
     * @memberof Channel
     * @example 777
     */
    assetLocalAmount?: number;

    /**
     * @type {number}
     * @memberof Channel
     * @example 0
     */
    assetRemoteAmount?: number;
}
