/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUtxosRequest
 */
export interface CreateUtxosRequest {

    /**
     * @type {boolean}
     * @memberof CreateUtxosRequest
     * @example false
     */
    upTo?: boolean;

    /**
     * @type {number}
     * @memberof CreateUtxosRequest
     * @example 4
     */
    num?: number;

    /**
     * @type {number}
     * @memberof CreateUtxosRequest
     * @example 32500
     */
    size?: number;

    /**
     * @type {number}
     * @memberof CreateUtxosRequest
     * @example 4.2
     */
    feeRate?: number;

    /**
     * @type {boolean}
     * @memberof CreateUtxosRequest
     * @example false
     */
    skipSync?: boolean;
}
