/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssetIface } from './asset-iface';
import { BitcoinNetwork } from './bitcoin-network';
 /**
 * 
 *
 * @export
 * @interface DecodeRGBInvoiceResponse
 */
export interface DecodeRGBInvoiceResponse {

    /**
     * @type {string}
     * @memberof DecodeRGBInvoiceResponse
     * @example utxob:2PoDFyk-8aegNHZE4-inHHn4nWz-rNtAX3MWv-sTiVPQYrF-ed2bXM
     */
    recipientId?: string;

    /**
     * @type {AssetIface}
     * @memberof DecodeRGBInvoiceResponse
     */
    assetIface?: AssetIface;

    /**
     * @type {string}
     * @memberof DecodeRGBInvoiceResponse
     * @example rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc
     */
    assetId?: string;

    /**
     * @type {number}
     * @memberof DecodeRGBInvoiceResponse
     * @example 69
     */
    amount?: number;

    /**
     * @type {BitcoinNetwork}
     * @memberof DecodeRGBInvoiceResponse
     */
    network?: BitcoinNetwork;

    /**
     * @type {number}
     * @memberof DecodeRGBInvoiceResponse
     * @example 1698325849
     */
    expirationTimestamp?: number;

    /**
     * @type {Array<string>}
     * @memberof DecodeRGBInvoiceResponse
     */
    transportEndpoints?: Array<string>;
}
