/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IssueAssetCFARequest
 */
export interface IssueAssetCFARequest {

    /**
     * @type {Array<number>}
     * @memberof IssueAssetCFARequest
     * @example [1000,600]
     */
    amounts?: Array<number>;

    /**
     * @type {string}
     * @memberof IssueAssetCFARequest
     * @example Tether
     */
    name?: string;

    /**
     * @type {string}
     * @memberof IssueAssetCFARequest
     * @example asset details
     */
    details?: string;

    /**
     * @type {number}
     * @memberof IssueAssetCFARequest
     * @example 0
     */
    precision?: number;

    /**
     * @type {string}
     * @memberof IssueAssetCFARequest
     * @example 5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03
     */
    fileDigest?: string;
}
