/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IssueAssetNIARequest
 */
export interface IssueAssetNIARequest {

    /**
     * @type {Array<number>}
     * @memberof IssueAssetNIARequest
     * @example [1000,600]
     */
    amounts?: Array<number>;

    /**
     * @type {string}
     * @memberof IssueAssetNIARequest
     * @example USDT
     */
    ticker?: string;

    /**
     * @type {string}
     * @memberof IssueAssetNIARequest
     * @example Tether
     */
    name?: string;

    /**
     * @type {number}
     * @memberof IssueAssetNIARequest
     * @example 0
     */
    precision?: number;
}
