/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IssueAssetUDARequest
 */
export interface IssueAssetUDARequest {

    /**
     * @type {string}
     * @memberof IssueAssetUDARequest
     * @example UNI
     */
    ticker?: string;

    /**
     * @type {string}
     * @memberof IssueAssetUDARequest
     * @example Unique
     */
    name?: string;

    /**
     * @type {string}
     * @memberof IssueAssetUDARequest
     * @example asset details
     */
    details?: string;

    /**
     * @type {number}
     * @memberof IssueAssetUDARequest
     * @example 0
     */
    precision?: number;

    /**
     * @type {string}
     * @memberof IssueAssetUDARequest
     * @example /path/to/media
     */
    mediaFileDigest?: string;

    /**
     * @type {Array<string>}
     * @memberof IssueAssetUDARequest
     * @example ["5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03","d7516e3a27cdf35aa9dcb323b5f556344ef7f57570be30b88de2bfd4ba339b1a"]
     */
    attachmentsFileDigests?: Array<string>;
}
