/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HTLCStatus } from './htlcstatus';
 /**
 * 
 *
 * @export
 * @interface KeysendResponse
 */
export interface KeysendResponse {

    /**
     * @type {string}
     * @memberof KeysendResponse
     * @example 8ffd4c0642047bc51ea01a22e6b2ede0fc001aee0e9929b2e84e41cf6589d61e
     */
    paymentHash?: string;

    /**
     * @type {string}
     * @memberof KeysendResponse
     * @example 89d28bd306aa9bb906fd0ac31092d04c37c919a171b343083167e2a3cdc60578
     */
    paymentPreimage?: string;

    /**
     * @type {HTLCStatus}
     * @memberof KeysendResponse
     */
    status?: HTLCStatus;
}
