/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssetCFA } from './asset-cfa';
import { AssetNIA } from './asset-nia';
import { AssetUDA } from './asset-uda';
 /**
 * 
 *
 * @export
 * @interface ListAssetsResponse
 */
export interface ListAssetsResponse {

    /**
     * @type {Array<AssetNIA>}
     * @memberof ListAssetsResponse
     */
    nia?: Array<AssetNIA>;

    /**
     * @type {Array<AssetUDA>}
     * @memberof ListAssetsResponse
     */
    uda?: Array<AssetUDA>;

    /**
     * @type {Array<AssetCFA>}
     * @memberof ListAssetsResponse
     */
    cfa?: Array<AssetCFA>;
}
