/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LNInvoiceRequest
 */
export interface LNInvoiceRequest {

    /**
     * @type {number}
     * @memberof LNInvoiceRequest
     * @example 3000000
     */
    amtMsat?: number;

    /**
     * @type {number}
     * @memberof LNInvoiceRequest
     * @example 420
     */
    expirySec?: number;

    /**
     * @type {string}
     * @memberof LNInvoiceRequest
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    assetId?: string;

    /**
     * @type {number}
     * @memberof LNInvoiceRequest
     * @example 42
     */
    assetAmount?: number;
}
