/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MakerInitRequest
 */
export interface MakerInitRequest {

    /**
     * @type {number}
     * @memberof MakerInitRequest
     * @example 30
     */
    qtyFrom?: number;

    /**
     * @type {number}
     * @memberof MakerInitRequest
     * @example 10
     */
    qtyTo?: number;

    /**
     * @type {string}
     * @memberof MakerInitRequest
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    fromAsset?: string;

    /**
     * @type {string}
     * @memberof MakerInitRequest
     * @example rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc
     */
    toAsset?: string;

    /**
     * @type {number}
     * @memberof MakerInitRequest
     * @example 100
     */
    timeoutSec?: number;
}
