/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MakerExecuteRequest
 */
export interface MakerExecuteRequest {

    /**
     * @type {string}
     * @memberof MakerExecuteRequest
     * @example 30/rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd/10/rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc/1715896416/9d342c6ba006e24abee84a2e034a22d5e30c1f2599fb9c3574d46d3cde3d65a2
     */
    swapstring?: string;

    /**
     * @type {string}
     * @memberof MakerExecuteRequest
     * @example 777a7756c620868199ed5fdc35bee4095b5709d543e5c2bf0494396bf27d2ea2
     */
    paymentSecret?: string;

    /**
     * @type {string}
     * @memberof MakerExecuteRequest
     * @example 02270dadcd6e7ba0ef707dac72acccae1a3607453a8dd2aef36ff3be4e0d31f043
     */
    takerPubkey?: string;
}
