/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface NodeInfoResponse
 */
export interface NodeInfoResponse {

    /**
     * @type {string}
     * @memberof NodeInfoResponse
     * @example 02270dadcd6e7ba0ef707dac72acccae1a3607453a8dd2aef36ff3be4e0d31f043
     */
    pubkey?: string;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 1
     */
    numChannels?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 0
     */
    numUsableChannels?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 28616000
     */
    localBalanceMsat?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 1
     */
    numPeers?: number;

    /**
     * @type {string}
     * @memberof NodeInfoResponse
     * @example tpubDDqiQYzNMGsKVVmWYG4FCPPcbd5S4uW9u7a6zUFkgbh16VmFTvsaNyo37mAgkCku6jStBcU8VaLxG2SE7ab2sEwwagjfbS8U9H82BadjKR1
     */
    onchainPubkey?: string;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 5
     */
    maxMediaUploadSizeMb?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 3000000
     */
    rgbHtlcMinMsat?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 30010
     */
    rgbChannelCapacityMinSat?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 5506
     */
    channelCapacityMinSat?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 16777215
     */
    channelCapacityMaxSat?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     * @example 1
     */
    channelAssetMinAmount?: number;

    /**
     * @type {number}
     * @memberof NodeInfoResponse
     */
    channelAssetMaxAmount?: number;
}
