/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OpenChannelResponse
 */
export interface OpenChannelResponse {

    /**
     * @type {string}
     * @memberof OpenChannelResponse
     * @example a8b60c8ce3067b5fc881d4831323e24751daec3b64353c8df3205ec5d838f1c5
     */
    temporaryChannelId?: string;
}
