/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OpenChannelRequest
 */
export interface OpenChannelRequest {

    /**
     * @type {string}
     * @memberof OpenChannelRequest
     * @example 03b79a4bc1ec365524b4fab9a39eb133753646babb5a1da5c4bc94c53110b7795d@localhost:9736
     */
    peerPubkeyAndOptAddr?: string;

    /**
     * @type {number}
     * @memberof OpenChannelRequest
     * @example 30010
     */
    capacitySat?: number;

    /**
     * @type {number}
     * @memberof OpenChannelRequest
     * @example 1394000
     */
    pushMsat?: number;

    /**
     * @type {number}
     * @memberof OpenChannelRequest
     * @example 333
     */
    assetAmount?: number;

    /**
     * @type {string}
     * @memberof OpenChannelRequest
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    assetId?: string;

    /**
     * @type {boolean}
     * @memberof OpenChannelRequest
     * @example true
     */
    _public?: boolean;

    /**
     * @type {boolean}
     * @memberof OpenChannelRequest
     * @example true
     */
    withAnchors?: boolean;

    /**
     * @type {number}
     * @memberof OpenChannelRequest
     * @example 1000
     */
    feeBaseMsat?: number;

    /**
     * @type {number}
     * @memberof OpenChannelRequest
     * @example 0
     */
    feeProportionalMillionths?: number;

    /**
     * @type {string}
     * @memberof OpenChannelRequest
     * @example a8b60c8ce3067b5fc881d4831323e24751daec3b64353c8df3205ec5d838f1c5
     */
    temporaryChannelId?: string;
}
