/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HTLCStatus } from './htlcstatus';
 /**
 * 
 *
 * @export
 * @interface Payment
 */
export interface Payment {

    /**
     * @type {number}
     * @memberof Payment
     * @example 3000000
     */
    amtMsat?: number;

    /**
     * @type {number}
     * @memberof Payment
     * @example 42
     */
    assetAmount?: number;

    /**
     * @type {string}
     * @memberof Payment
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    assetId?: string;

    /**
     * @type {string}
     * @memberof Payment
     * @example 3febfae1e68b190c15461f4c2a3290f9af1dae63fd7d620d2bd61601869026cd
     */
    paymentHash?: string;

    /**
     * @type {boolean}
     * @memberof Payment
     * @example true
     */
    inbound?: boolean;

    /**
     * @type {HTLCStatus}
     * @memberof Payment
     */
    status?: HTLCStatus;
}
