/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RgbInvoiceResponse
 */
export interface RgbInvoiceResponse {

    /**
     * @type {string}
     * @memberof RgbInvoiceResponse
     * @example utxob:2FZsSuk-iyVQLVuU4-Gc6J4qkE8-mLS17N4jd-MEx6cWz9F-MFkyE1n
     */
    recipientId?: string;

    /**
     * @type {string}
     * @memberof RgbInvoiceResponse
     * @example rgb:~/~/utxob:2FZsSuk-iyVQLVuU4-Gc6J4qkE8-mLS17N4jd-MEx6cWz9F-MFkyE1n?expiry=1695811760&endpoints=rpc://127.0.0.1:3000/json-rpc
     */
    invoice?: string;

    /**
     * @type {number}
     * @memberof RgbInvoiceResponse
     * @example 1695811760
     */
    expirationTimestamp?: number;
}
