/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendBtcResponse
 */
export interface SendBtcResponse {

    /**
     * @type {string}
     * @memberof SendBtcResponse
     * @example 7c2c95b9c2aa0a7d140495b664de7973b76561de833f0dd84def3efa08941664
     */
    txid?: string;
}
