/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendOnionMessageRequest
 */
export interface SendOnionMessageRequest {

    /**
     * @type {Array<string>}
     * @memberof SendOnionMessageRequest
     */
    nodeIds?: Array<string>;

    /**
     * @type {number}
     * @memberof SendOnionMessageRequest
     * @example 77
     */
    tlvType?: number;

    /**
     * @type {string}
     * @memberof SendOnionMessageRequest
     * @example message to send
     */
    data?: string;
}
