/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HTLCStatus } from './htlcstatus';
 /**
 * 
 *
 * @export
 * @interface SendPaymentResponse
 */
export interface SendPaymentResponse {

    /**
     * @type {string}
     * @memberof SendPaymentResponse
     * @example 3febfae1e68b190c15461f4c2a3290f9af1dae63fd7d620d2bd61601869026cd
     */
    paymentHash?: string;

    /**
     * @type {string}
     * @memberof SendPaymentResponse
     * @example 777a7756c620868199ed5fdc35bee4095b5709d543e5c2bf0494396bf27d2ea2
     */
    paymentSecret?: string;

    /**
     * @type {HTLCStatus}
     * @memberof SendPaymentResponse
     */
    status?: HTLCStatus;
}
