/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendBtcRequest
 */
export interface SendBtcRequest {

    /**
     * @type {number}
     * @memberof SendBtcRequest
     * @example 16900
     */
    amount?: number;

    /**
     * @type {string}
     * @memberof SendBtcRequest
     * @example bcrt1qwxht5tut39dws8tjcf649tp908r8fr2j75c94k
     */
    address?: string;

    /**
     * @type {number}
     * @memberof SendBtcRequest
     * @example 4.2
     */
    feeRate?: number;

    /**
     * @type {boolean}
     * @memberof SendBtcRequest
     * @example false
     */
    skipSync?: boolean;
}
