/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SwapStatus } from './swap-status';
 /**
 * 
 *
 * @export
 * @interface Swap
 */
export interface Swap {

    /**
     * @type {number}
     * @memberof Swap
     * @example 30
     */
    qtyFrom?: number;

    /**
     * @type {number}
     * @memberof Swap
     * @example 10
     */
    qtyTo?: number;

    /**
     * @type {string}
     * @memberof Swap
     * @example rgb:2dkSTbr-jFhznbPmo-TQafzswCN-av4gTsJjX-ttx6CNou5-M98k8Zd
     */
    fromAsset?: string;

    /**
     * @type {string}
     * @memberof Swap
     * @example rgb:2eVw8uw-8G88LQ2tQ-kexM12SoD-nCX8DmQrw-yLMu6JDfK-xx1SCfc
     */
    toAsset?: string;

    /**
     * @type {string}
     * @memberof Swap
     * @example 7c2c95b9c2aa0a7d140495b664de7973b76561de833f0dd84def3efa08941664
     */
    paymentHash?: string;

    /**
     * @type {SwapStatus}
     * @memberof Swap
     */
    status?: SwapStatus;

    /**
     * @type {number}
     * @memberof Swap
     * @example 1691160765
     */
    requestedAt?: number;

    /**
     * @type {number}
     * @memberof Swap
     * @example 1691168512
     */
    initiatedAt?: number;

    /**
     * @type {number}
     * @memberof Swap
     * @example 1691172703
     */
    expiresAt?: number;

    /**
     * @type {number}
     * @memberof Swap
     * @example 1691171075
     */
    completedAt?: number;
}
