/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Media } from './media';
 /**
 * 
 *
 * @export
 * @interface TokenLight
 */
export interface TokenLight {

    /**
     * @type {number}
     * @memberof TokenLight
     * @example 0
     */
    index?: number;

    /**
     * @type {string}
     * @memberof TokenLight
     * @example TKN
     */
    ticker?: string;

    /**
     * @type {string}
     * @memberof TokenLight
     * @example Token
     */
    name?: string;

    /**
     * @type {string}
     * @memberof TokenLight
     * @example token details
     */
    details?: string;

    /**
     * @type {boolean}
     * @memberof TokenLight
     * @example true
     */
    embeddedMedia?: boolean;

    /**
     * @type {Media}
     * @memberof TokenLight
     */
    media?: Media;

    /**
     * @type {{ [key: string]: Media; }}
     * @memberof TokenLight
     * @example {"0":{"file_path":"path/to/attachment0","digest":"5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03","mime":"text/plain"},"1":{"file_path":"path/to/attachment1","digest":"d7516e3a27cdf35aa9dcb323b5f556344ef7f57570be30b88de2bfd4ba339b1a","mime":"image/png"}}
     */
    attachments?: { [key: string]: Media; };

    /**
     * @type {boolean}
     * @memberof TokenLight
     * @example false
     */
    reserves?: boolean;
}
