/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransportType } from './transport-type';
 /**
 * 
 *
 * @export
 * @interface TransferTransportEndpoint
 */
export interface TransferTransportEndpoint {

    /**
     * @type {string}
     * @memberof TransferTransportEndpoint
     * @example http://127.0.0.1:3000/json-rpc
     */
    endpoint?: string;

    /**
     * @type {TransportType}
     * @memberof TransferTransportEndpoint
     */
    transportType?: TransportType;

    /**
     * @type {boolean}
     * @memberof TransferTransportEndpoint
     * @example false
     */
    used?: boolean;
}
