/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BlockTime } from './block-time';
import { TransactionType } from './transaction-type';
 /**
 * 
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {

    /**
     * @type {TransactionType}
     * @memberof Transaction
     */
    transactionType?: TransactionType;

    /**
     * @type {string}
     * @memberof Transaction
     * @example 7c2c95b9c2aa0a7d140495b664de7973b76561de833f0dd84def3efa08941664
     */
    txid?: string;

    /**
     * @type {number}
     * @memberof Transaction
     * @example 650
     */
    received?: number;

    /**
     * @type {number}
     * @memberof Transaction
     * @example 1050
     */
    sent?: number;

    /**
     * @type {number}
     * @memberof Transaction
     * @example 100
     */
    fee?: number;

    /**
     * @type {BlockTime}
     * @memberof Transaction
     */
    confirmationTime?: BlockTime;
}
