/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransferKind } from './transfer-kind';
import { TransferStatus } from './transfer-status';
import { TransferTransportEndpoint } from './transfer-transport-endpoint';
 /**
 * 
 *
 * @export
 * @interface Transfer
 */
export interface Transfer {

    /**
     * @type {number}
     * @memberof Transfer
     * @example 1
     */
    idx?: number;

    /**
     * @type {number}
     * @memberof Transfer
     * @example 1691160765
     */
    createdAt?: number;

    /**
     * @type {number}
     * @memberof Transfer
     * @example 1691162674
     */
    updatedAt?: number;

    /**
     * @type {TransferStatus}
     * @memberof Transfer
     */
    status?: TransferStatus;

    /**
     * @type {number}
     * @memberof Transfer
     * @example 77
     */
    amount?: number;

    /**
     * @type {TransferKind}
     * @memberof Transfer
     */
    kind?: TransferKind;

    /**
     * @type {string}
     * @memberof Transfer
     * @example 7c2c95b9c2aa0a7d140495b664de7973b76561de833f0dd84def3efa08941664
     */
    txid?: string;

    /**
     * @type {string}
     * @memberof Transfer
     * @example 61qsVbWtkNmU54F2i6qtB9uSmEGsPoaeypCi5uC5uctZ
     */
    recipientId?: string;

    /**
     * @type {string}
     * @memberof Transfer
     * @example efed66f5309396ff43c8a09941c8103d9d5bbffd473ad9f13013ac89fb6b4671:0
     */
    receiveUtxo?: string;

    /**
     * @type {string}
     * @memberof Transfer
     */
    changeUtxo?: string;

    /**
     * @type {number}
     * @memberof Transfer
     * @example 1691171612
     */
    expiration?: number;

    /**
     * @type {Array<TransferTransportEndpoint>}
     * @memberof Transfer
     */
    transportEndpoints?: Array<TransferTransportEndpoint>;
}
