/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UnlockRequest
 */
export interface UnlockRequest {

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example nodepassword
     */
    password?: string;

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example user
     */
    bitcoindRpcUsername?: string;

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example password
     */
    bitcoindRpcPassword?: string;

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example localhost
     */
    bitcoindRpcHost?: string;

    /**
     * @type {number}
     * @memberof UnlockRequest
     * @example 18443
     */
    bitcoindRpcPort?: number;

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example 127.0.0.1:50001
     */
    indexerUrl?: string;

    /**
     * @type {string}
     * @memberof UnlockRequest
     * @example rpc://127.0.0.1:3000/json-rpc
     */
    proxyEndpoint?: string;
}
