/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Utxo
 */
export interface Utxo {

    /**
     * @type {string}
     * @memberof Utxo
     * @example efed66f5309396ff43c8a09941c8103d9d5bbffd473ad9f13013ac89fb6b4671:0
     */
    outpoint?: string;

    /**
     * @type {number}
     * @memberof Utxo
     * @example 1000
     */
    btcAmount?: number;

    /**
     * @type {boolean}
     * @memberof Utxo
     * @example true
     */
    colorable?: boolean;
}
