/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DecodeLNInvoiceRequest } from '../models';
import { DecodeLNInvoiceResponse } from '../models';
import { InvoiceStatusRequest } from '../models';
import { InvoiceStatusResponse } from '../models';
import { LNInvoiceRequest } from '../models';
import { LNInvoiceResponse } from '../models';
/**
 * InvoicesApi - axios parameter creator
 * @export
 */
export const InvoicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Decode the provided LN invoice string
         * @summary Decode a LN invoice
         * @param {DecodeLNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        decodelninvoicePost: async (body?: DecodeLNInvoiceRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/decodelninvoice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the status of the provided LN invoice
         * @summary Get an invoice status
         * @param {InvoiceStatusRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoicestatusPost: async (body?: InvoiceStatusRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoicestatus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a LN invoice to receive a payment
         * @summary Get a LN invoice
         * @param {LNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lninvoicePost: async (body?: LNInvoiceRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/lninvoice`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoicesApi - functional programming interface
 * @export
 */
export const InvoicesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Decode the provided LN invoice string
         * @summary Decode a LN invoice
         * @param {DecodeLNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async decodelninvoicePost(body?: DecodeLNInvoiceRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DecodeLNInvoiceResponse>>> {
            const localVarAxiosArgs = await InvoicesApiAxiosParamCreator(configuration).decodelninvoicePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get the status of the provided LN invoice
         * @summary Get an invoice status
         * @param {InvoiceStatusRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invoicestatusPost(body?: InvoiceStatusRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InvoiceStatusResponse>>> {
            const localVarAxiosArgs = await InvoicesApiAxiosParamCreator(configuration).invoicestatusPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get a LN invoice to receive a payment
         * @summary Get a LN invoice
         * @param {LNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lninvoicePost(body?: LNInvoiceRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LNInvoiceResponse>>> {
            const localVarAxiosArgs = await InvoicesApiAxiosParamCreator(configuration).lninvoicePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InvoicesApi - factory interface
 * @export
 */
export const InvoicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Decode the provided LN invoice string
         * @summary Decode a LN invoice
         * @param {DecodeLNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async decodelninvoicePost(body?: DecodeLNInvoiceRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<DecodeLNInvoiceResponse>> {
            return InvoicesApiFp(configuration).decodelninvoicePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the status of the provided LN invoice
         * @summary Get an invoice status
         * @param {InvoiceStatusRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invoicestatusPost(body?: InvoiceStatusRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<InvoiceStatusResponse>> {
            return InvoicesApiFp(configuration).invoicestatusPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a LN invoice to receive a payment
         * @summary Get a LN invoice
         * @param {LNInvoiceRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lninvoicePost(body?: LNInvoiceRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<LNInvoiceResponse>> {
            return InvoicesApiFp(configuration).lninvoicePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvoicesApi - object-oriented interface
 * @export
 * @class InvoicesApi
 * @extends {BaseAPI}
 */
export class InvoicesApi extends BaseAPI {
    /**
     * Decode the provided LN invoice string
     * @summary Decode a LN invoice
     * @param {DecodeLNInvoiceRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public async decodelninvoicePost(body?: DecodeLNInvoiceRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<DecodeLNInvoiceResponse>> {
        return InvoicesApiFp(this.configuration).decodelninvoicePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get the status of the provided LN invoice
     * @summary Get an invoice status
     * @param {InvoiceStatusRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public async invoicestatusPost(body?: InvoiceStatusRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<InvoiceStatusResponse>> {
        return InvoicesApiFp(this.configuration).invoicestatusPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get a LN invoice to receive a payment
     * @summary Get a LN invoice
     * @param {LNInvoiceRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoicesApi
     */
    public async lninvoicePost(body?: LNInvoiceRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<LNInvoiceResponse>> {
        return InvoicesApiFp(this.configuration).lninvoicePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
