/* tslint:disable */
/* eslint-disable */
/**
 * RGB Lightning Node
 * This is the OpenAPI specification for the [RGB Lightning Node](https://github.com/RGB-Tools/rgb-lightning-node) APIs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EmptyResponse } from '../models';
import { ListSwapsResponse } from '../models';
import { MakerExecuteRequest } from '../models';
import { MakerInitRequest } from '../models';
import { MakerInitResponse } from '../models';
import { TakerRequest } from '../models';
/**
 * SwapsApi - axios parameter creator
 * @export
 */
export const SwapsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List the node's swaps
         * @summary List swaps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listswapsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listswaps`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Execute a swap on the maker side
         * @summary Execute a maker swap
         * @param {MakerExecuteRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        makerexecutePost: async (body?: MakerExecuteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/makerexecute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Init a swap on the maker side
         * @summary Init a maker swap
         * @param {MakerInitRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        makerinitPost: async (body?: MakerInitRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/makerinit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Accept a swap on the taker side
         * @summary Accept a swap
         * @param {TakerRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        takerPost: async (body?: TakerRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/taker`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SwapsApi - functional programming interface
 * @export
 */
export const SwapsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * List the node's swaps
         * @summary List swaps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listswapsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ListSwapsResponse>>> {
            const localVarAxiosArgs = await SwapsApiAxiosParamCreator(configuration).listswapsGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Execute a swap on the maker side
         * @summary Execute a maker swap
         * @param {MakerExecuteRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async makerexecutePost(body?: MakerExecuteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await SwapsApiAxiosParamCreator(configuration).makerexecutePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Init a swap on the maker side
         * @summary Init a maker swap
         * @param {MakerInitRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async makerinitPost(body?: MakerInitRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MakerInitResponse>>> {
            const localVarAxiosArgs = await SwapsApiAxiosParamCreator(configuration).makerinitPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Accept a swap on the taker side
         * @summary Accept a swap
         * @param {TakerRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async takerPost(body?: TakerRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await SwapsApiAxiosParamCreator(configuration).takerPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SwapsApi - factory interface
 * @export
 */
export const SwapsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * List the node's swaps
         * @summary List swaps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listswapsGet(options?: AxiosRequestConfig): Promise<AxiosResponse<ListSwapsResponse>> {
            return SwapsApiFp(configuration).listswapsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Execute a swap on the maker side
         * @summary Execute a maker swap
         * @param {MakerExecuteRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async makerexecutePost(body?: MakerExecuteRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return SwapsApiFp(configuration).makerexecutePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Init a swap on the maker side
         * @summary Init a maker swap
         * @param {MakerInitRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async makerinitPost(body?: MakerInitRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<MakerInitResponse>> {
            return SwapsApiFp(configuration).makerinitPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Accept a swap on the taker side
         * @summary Accept a swap
         * @param {TakerRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async takerPost(body?: TakerRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return SwapsApiFp(configuration).takerPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SwapsApi - object-oriented interface
 * @export
 * @class SwapsApi
 * @extends {BaseAPI}
 */
export class SwapsApi extends BaseAPI {
    /**
     * List the node's swaps
     * @summary List swaps
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwapsApi
     */
    public async listswapsGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<ListSwapsResponse>> {
        return SwapsApiFp(this.configuration).listswapsGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Execute a swap on the maker side
     * @summary Execute a maker swap
     * @param {MakerExecuteRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwapsApi
     */
    public async makerexecutePost(body?: MakerExecuteRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return SwapsApiFp(this.configuration).makerexecutePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Init a swap on the maker side
     * @summary Init a maker swap
     * @param {MakerInitRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwapsApi
     */
    public async makerinitPost(body?: MakerInitRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<MakerInitResponse>> {
        return SwapsApiFp(this.configuration).makerinitPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Accept a swap on the taker side
     * @summary Accept a swap
     * @param {TakerRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SwapsApi
     */
    public async takerPost(body?: TakerRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return SwapsApiFp(this.configuration).takerPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
